[versions]
agp = "8.13.2"
androidCompileSdk = "36"
androidMinSdk = "29"
androidTargetSdk = "36"
activity = "1.12.3"
core = "1.17.0"
lifecycle = "2.9.6"
lifecycleKtx = "2.10.0"
composeBom = "2026.01.01"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.10.0"
ktor = "3.4.0"
uiTooling = "1.10.2"
koin = "4.1.1"
ksp = "2.3.4"
material3 = "1.5.0-alpha13"
room = "2.8.4"
sqlite = "2.6.2"
koinPlugin = "0.2.9"
paging = "3.4.0"
skie = "0.10.9"
turbine = "1.1.0"
mokkery = "3.1.1"
nav3Core = "1.0.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiTooling" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
mokkery = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
paging = { module = "androidx.paging:paging-common", version.ref = "paging" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
koinCompiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koinPlugin" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
